# installing tomcat on Ubuntu servers

- name: Install tomcat-9
  hosts: all
  become: yes
  tasks:
  - name: apt update & install java
    package:
      update_cache: true
      name: openjdk-11-jdk
      state: present
  
  - name: create user tomcat
    user:
      name: tomcat
      home: /opt/tomcat
      shell: /bin/false

  - name: download tomcat-9 tar.gz file
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.74/bin/apache-tomcat-9.0.74.tar.gz
      dest: /tmp/apache-tomcat-9.0.74.tar.gz

  - name: extract tar.gz file to /opt/tomcat
    unarchive:
      dest: /opt/tomcat         # absolute path
      remote_src: true  # Set to true to indicate the archived file is already on the remote system and not local to the Ansible controller.
      src: /tmp/apache-tomcat-9.0.74.tar.gz
      creates: /opt/tomcat/apache-tomcat-9.0.74    # If the specified absolute path (file or directory) already exists, this step will not be run.


# Tomcat is updated on a regular basis with security patches and new features. To have more control over versions and updates, we’ll - 
# create a symbolic link called latest, that points to the Tomcat installation directory.
  - name: create symbolic link "latest"
    file:
      src: /opt/tomcat/apache-tomcat-9.0.74      # command format --> "ln -s src dest"
      path: /opt/tomcat/latest   # dest
      state: link

  - name: make tomcat user as the owner for /opt/tomcat/ directory 
    file:
      state: directory
      path: /opt/tomcat/
      owner: tomcat
      group: tomcat
      recurse: true        # applies this ownership recursively to all files inside the directory.