- name: install lamp stack on Ubuntu & RedHat servers
  hosts: all
  become: yes
  tasks:

  - name: apt update and install apache2
    apt:
      name: apache2
      state: present
      update_cache: true                                       # true/false
    when: ansible_facts['distribution'] == 'Ubuntu'     # conditionals     # refer Notes file

  - name: install php libapache2-mod-php php-mysql
    apt:
      name:
      - php
      - libapache2-mod-php
      - php-mysql
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: yum update and install httpd
    yum:
      name: httpd
      state: present
      update_cache: true
    when: ansible_facts['distribution'] == 'RedHat'

  - name: start & enable httpd
    service:
      name: httpd
      state: started  # started is idempotent  # service will not be started again when ran after the 1st time   # see Notes file
      enabled: true
    when: ansible_facts['distribution'] == 'RedHat'

  - name: install php libapache2-mod-php php-mysql
    yum:
      name:
        - php
        - php-cli
        - php-mysqlnd
      state: present
    when: ansible_facts['distribution'] == 'RedHat'

  
  - name: create info.php             # echo "<?php phpinfo(); ?>" | sudo tee /var/www/html/info.php
    copy:
      dest: /var/www/html/info.php       # Creates the file if it does not exist.
      content: |
        <?php
        phpinfo();
        ?>
    notify:
    - restart apache2      # notify
    - restart httpd

  handlers:                   # use of handlers
  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: ansible_facts['distribution'] == 'RedHat'
