jdk_file: openjdk-11-jdk
jdk_file_centos: java-1.8.0-openjdk-devel
tomcat_username: tomcat
tomcat_home: /opt/tomcat
tomcat_shell: /bin/false
tomcat_version: '9.0.54'
tomcat_users_config_location: /opt/tomcat/latest/conf/tomcat-users.xml
tomcat_manager_config_location: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
tomcat_host_manager_config_location: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
