# To uninstall OpenJDK: - 

# PRE-REQ: stop tomcat.service, delete the unit file & do systemctl daemon-reload

# 1) First check which OpenJDK packages are installed.
# sudo dpkg --list | grep -i jdk

# 2) Uninstall OpenJDK related packages.
# sudo apt-get purge icedtea-* openjdk-* -y

# 3) Check that all OpenJDK packages have been removed.
# sudo dpkg --list | grep -i jdk



- name: Uninstall tomcat on Ubuntu servers
  hosts: all
  become: yes
  tasks:
    - name: Uninstall Java on Ubuntu
      package:
        name: openjdk-11-jdk
        state: absent    

    - name: delete tomcat tar file
      file:
        path: "/tmp/apache-tomcat-{{ tomcat_minor_version }}.tar.gz"
        state: absent
   
    # by deleting /opt/tomcat/latest sim link, all files under it will be deleted (tomcat-users.xml, manager/context.xml & host-manager/context.xml)     
    - name: delete the "latest" sim link
      file:
        path: /opt/tomcat/latest
        state: absent

    - name: delete the unzipped tomcat tar file 
      file:
        path: /opt/tomcat/apache-tomcat-{{ tomcat_minor_version }}
        state: absent

    - name: delete tomcat.service file on Ubuntu
      file:
        path: /etc/systemd/system/tomcat.service
        state: absent

    - name: delete tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: absent
        force: yes